@extends('layouts.frontend.main')
@section('title', 'Global Sourcing | Alberta International Traders')
@section('content')
@include('frontend.shared.company-page-styles')
<section class="rts__breadcrumb__area"><div class="container"><div class="row"><div class="col-lg-12"><div class="rts__breadcrumb__content" data-bg-src="https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&amp;fit=crop&amp;w=1600&amp;q=85"><ul class="list"><li><a href="{{ route('home') }}">Home</a></li><li><i class="fa-solid fa-chevron-right"></i></li><li>Global Sourcing</li></ul><h2 class="title rts-text-anime">Global Sourcing</h2></div></div></div></div></section>
<section class="rts-section-gap"><div class="container">
<div class="row g-5 align-items-center mb-5"><div class="col-lg-6"><img class="company-page-image" src="https://images.unsplash.com/photo-1581092160562-40aa08e78837?auto=format&amp;fit=crop&amp;w=1200&amp;q=85" alt="Global industrial product sourcing"></div><div class="col-lg-6"><div class="section-title"><span class="sub-title">Worldwide Supply Network</span><h2 class="heading-title-two">The Right Product from the Right Source</h2><p>AIT creates commercial flows by importing and exporting products and connecting customers with an extensive global network of suppliers, contacts and sources.</p><p>We identify suitable brands, technologies and supply options based on each customer's technical, commercial and delivery requirements.</p></div><a href="{{ route('quote') }}" class="rts-btn btn-primary">Submit Your Requirement <i class="fa-solid fa-arrow-right"></i></a></div></div>
<div class="section-title text-center mb-5"><span class="sub-title">How We Work</span><h2 class="heading-title-two">Sourcing from Requirement to Delivery</h2></div><div class="row g-4">@foreach([['fa-magnifying-glass','Understand Requirements','We review specifications, quantities, preferred brands, condition and delivery expectations.'],['fa-earth-americas','Source Globally','Our network helps identify reputable manufacturers, suppliers and competitive alternatives.'],['fa-scale-balanced','Evaluate Options','We compare product suitability, quality, pricing and availability for informed decisions.'],['fa-truck-fast','Coordinate Supply','We support commercial flow and supply-chain coordination through delivery to the customer.']] as $item)<div class="col-lg-3 col-md-6"><div class="company-feature-card"><i class="fa-solid {{ $item[0] }}"></i><h4>{{ $item[1] }}</h4><p>{{ $item[2] }}</p></div></div>@endforeach</div>
</div></section>
<!-- @include('frontend.shared.company-cta') -->
@endsection
