@extends('layouts.frontend.main')
@section('title', 'Partners & Vendors | Alberta International Traders')
@section('content')
@include('frontend.shared.company-page-styles')
<section class="rts__breadcrumb__area"><div class="container"><div class="row"><div class="col-lg-12"><div class="rts__breadcrumb__content" data-bg-src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&amp;fit=crop&amp;w=1600&amp;q=85"><ul class="list"><li><a href="{{ route('home') }}">Home</a></li><li><i class="fa-solid fa-chevron-right"></i></li><li>Partners & Vendors</li></ul><h2 class="title rts-text-anime">Partners & Vendors</h2></div></div></div></div></section>
<section class="rts-section-gap"><div class="container">
<div class="row g-5 align-items-center mb-5"><div class="col-lg-6"><div class="section-title"><span class="sub-title">Enduring Business Relationships</span><h2 class="heading-title-two">A Global Network Built on Trust</h2><p>AIT fosters growth and lasting business ties with clients, principals, suppliers and vendors. Open and honest communication is the foundation for building respect, trust and loyalty.</p><p>We work as a team with our partners to provide quality products, reliable service, market information and responsive support to customers.</p></div><a href="{{ route('contact') }}" class="rts-btn btn-primary">Partner with AIT <i class="fa-solid fa-arrow-right"></i></a></div><div class="col-lg-6"><img class="company-page-image" src="https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&amp;fit=crop&amp;w=1200&amp;q=85" alt="AIT partners and vendors"></div></div>
<div class="row g-4">@foreach([['fa-handshake','Strong Relationships','We invest in relationships that support a shared vision and create long-term value.'],['fa-award','Quality Commitment','We prioritize reputable manufacturers and products that meet customer quality requirements.'],['fa-comments','Open Communication','Transparent communication supports trust, timely information and effective collaboration.'],['fa-people-group','Teamwork','Combined expertise and coordinated effort help every partner perform to a high standard.'],['fa-chart-line','Market Partnership','We support principals with sales objectives, market information and customer service.'],['fa-globe','Global Reach','Our international supplier network expands access to brands, options and technologies.']] as $item)<div class="col-lg-4 col-md-6"><div class="company-feature-card"><i class="fa-solid {{ $item[0] }}"></i><h4>{{ $item[1] }}</h4><p>{{ $item[2] }}</p></div></div>@endforeach</div>
</div></section>
<!-- @include('frontend.shared.company-cta') -->
@endsection
