@php($editing = isset($product))
@if ($errors->any())
<div class="alert alert-danger"><strong>Please fix the following:</strong><ul class="mb-0 mt-2">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>
@endif

<div class="row">
    <div class="col-lg-8">
        <h4 class="mb-4 fw-bold"><i class="fas fa-box text-primary me-2"></i>{{ $editing ? 'Edit Product' : 'Create New Product' }}</h4>
        <div class="row">
            <div class="col-md-6 mb-4"><label class="form-label">Category <span class="text-danger">*</span></label><select name="category_id" class="form-select" required><option value="">Select Category</option>@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id', $product->category_id ?? '') == $category->id)>{{ $category->name }}</option>@endforeach</select></div>
            <div class="col-md-6 mb-4"><label class="form-label">SKU</label><input class="form-control bg-light" value="{{ $product->sku ?? $nextSku }}" disabled readonly><small class="text-muted">Automatically generated by the system.</small></div>
        </div>
        <div class="mb-4"><label class="form-label">Product Name <span class="text-danger">*</span></label><input name="name" id="productName" class="form-control" value="{{ old('name', $product->name ?? '') }}" required></div>
        <div class="mb-4"><label class="form-label">Slug</label><input name="slug" id="productSlug" class="form-control" value="{{ old('slug', $product->slug ?? '') }}" placeholder="Auto-generated from product name"><small class="text-muted">Leave blank to generate automatically.</small></div>
        <div class="row">
            <div class="col-md-4 mb-4"><label class="form-label">Purchase Price <span class="text-danger">*</span></label><input type="number" step="0.01" min="0" name="purchase_price" class="form-control" value="{{ old('purchase_price', $product->purchase_price ?? 0) }}" required></div>
            <div class="col-md-4 mb-4"><label class="form-label">Sale Price <span class="text-danger">*</span></label><input type="number" step="0.01" min="0" name="sale_price" class="form-control" value="{{ old('sale_price', $product->sale_price ?? 0) }}" required></div>
            <div class="col-md-4 mb-4"><label class="form-label">Stock Quantity <span class="text-danger">*</span></label><input type="number" min="0" name="stock_quantity" class="form-control" value="{{ old('stock_quantity', $product->stock_quantity ?? 0) }}" required></div>
        </div>
        <div class="mb-4"><label class="form-label">Short Description</label><textarea name="short_description" class="form-control" rows="3">{{ old('short_description', $product->short_description ?? '') }}</textarea></div>
        <div class="mb-4"><label class="form-label">Long Description (Rich Text)</label><textarea id="summernote" name="long_description">{{ old('long_description', $product->long_description ?? '') }}</textarea></div>
    </div>
    <div class="col-lg-4">
        <div class="p-3 bg-light rounded-4 mb-4">
            <h6 class="fw-bold mb-3">Product Settings</h6>
            <div class="mb-4"><label class="form-label">Status</label><select name="status" class="form-select"><option value="active" @selected(old('status', $product->status ?? 'active') === 'active')>Active</option><option value="inactive" @selected(old('status', $product->status ?? 'active') === 'inactive')>Inactive</option></select></div>
            <label class="form-label">Feature Image</label><input type="file" name="feature_image" class="form-control" accept="image/*" id="featureImageInput">
            <div class="mt-2 text-center border rounded-3 p-2 bg-white" style="min-height:130px;display:flex;align-items:center;justify-content:center"><img id="featureImagePreview" src="{{ $editing && $product->feature_image ? $product->feature_image_url : '' }}" style="max-width:100%;max-height:170px;{{ $editing && $product->feature_image ? '' : 'display:none' }}"><span id="imagePlaceholder" class="text-muted" @if($editing && $product->feature_image) style="display:none" @endif><i class="fas fa-image fa-2x d-block mb-2"></i>Select an image</span></div>
        </div>
        <div class="p-3 bg-light rounded-4">
            <h6 class="fw-bold mb-3">Gallery Images</h6><input type="file" name="gallery_images[]" class="form-control" accept="image/*" multiple id="galleryInput">
            @if($editing)<div class="row g-2 mt-2" id="savedGallery">@foreach($product->galleries as $gallery)<div class="col-4 position-relative" id="gallery-{{ $gallery->id }}"><img src="{{ Storage::url($gallery->image) }}" class="rounded w-100" style="height:80px;object-fit:cover"><button type="button" class="btn btn-danger btn-sm position-absolute top-0 end-0" onclick="deleteGallery({{ $gallery->id }})">&times;</button></div>@endforeach</div>@endif
            <div id="galleryPreview" class="row g-2 mt-2"></div>
        </div>
    </div>
</div>
<div class="mt-4 pt-3 border-top text-end"><a href="{{ route('products.index') }}" class="btn btn-light rounded-pill px-4 me-2">Cancel</a><button class="btn btn-primary rounded-pill px-5 fw-bold"><i class="fas fa-save me-2"></i>{{ $editing ? 'Update Product' : 'Save Product' }}</button></div>

@section('scripts')
<script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/summernote@0.8.18/dist/summernote-lite.min.js"></script>
<script>
$(function(){
 $('#summernote').summernote({height:300,placeholder:'Write detailed product information...'});
 $('#featureImageInput').on('change',function(){let f=this.files[0];if(!f)return;let r=new FileReader;r.onload=e=>{$('#featureImagePreview').attr('src',e.target.result).show();$('#imagePlaceholder').hide()};r.readAsDataURL(f)});
 $('#galleryInput').on('change',function(){$('#galleryPreview').empty();[...this.files].forEach(f=>{let r=new FileReader;r.onload=e=>$('#galleryPreview').append(`<div class="col-4"><img src="${e.target.result}" class="rounded w-100" style="height:80px;object-fit:cover"></div>`);r.readAsDataURL(f)})});
});
function deleteGallery(id){if(!confirm('Delete this gallery image?'))return;$.ajax({url:`{{ url('/products/gallery') }}/${id}`,type:'DELETE',data:{_token:'{{ csrf_token() }}'},success:()=>$('#gallery-'+id).remove(),error:()=>alert('Unable to delete image.')})}
</script>
@endsection
