@extends('layouts.frontend.main')
@section('title', 'Projects | Alberta International Traders')
@section('content')
@include('frontend.shared.company-page-styles')
<section class="rts__breadcrumb__area"><div class="container"><div class="row"><div class="col-lg-12"><div class="rts__breadcrumb__content" data-bg-src="https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&amp;fit=crop&amp;w=1600&amp;q=85"><ul class="list"><li><a href="{{ route('home') }}">Home</a></li><li><i class="fa-solid fa-chevron-right"></i></li><li>Projects</li></ul><h2 class="title rts-text-anime">International Projects</h2></div></div></div></div></section>
<section class="rts-section-gap"><div class="container">
<div class="section-title text-center mb-5"><span class="sub-title">Project Capabilities</span><h2 class="heading-title-two">Coordinating Industrial Requirements Across Borders</h2><p class="mx-auto" style="max-width:850px;">AIT arranges and manages international projects with its partners, supporting customers with sourcing, commercial coordination and reliable supply across four core business lines.</p></div>
@php($projects=[['Industrial Equipment Supply','Engines, turbines, pumps, fire hydrants, oil field machinery and general machinery sourced according to operational needs.','https://images.unsplash.com/photo-1565793298595-6a879b1d9492?auto=format&fit=crop&w=1100&q=85'],['Construction Equipment Procurement','Equipment selection and sourcing support for cranes, Bobcats, bulldozers, loaders, dump trucks, backhoes and excavators.','https://images.unsplash.com/photo-1531834685032-c34bf0d84c77?auto=format&fit=crop&w=1100&q=85'],['Construction Material Supply','Professional-grade natural materials, wood, brick, block, metal, glass, ceramics, plastic and foam for demanding projects.','https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1100&q=85'],['Food & Beverage Plant Equipment','New and used processing, packaging, mixing, filtering, heating, drying and storage equipment from major manufacturers.','https://images.unsplash.com/photo-1565514020179-026b92b84bb6?auto=format&fit=crop&w=1100&q=85']])
<div class="row g-4">@foreach($projects as $project)<div class="col-lg-6"><div class="company-project-card"><img src="{{ $project[2] }}" alt="{{ $project[0] }}"><div class="content"><span>Project Capability {{ sprintf('%02d',$loop->iteration) }}</span><h3>{{ $project[0] }}</h3><p>{{ $project[1] }}</p><a href="{{ route('quote') }}">Discuss a Requirement <i class="fa-solid fa-arrow-right"></i></a></div></div></div>@endforeach</div>
</div></section>
<!-- @include('frontend.shared.company-cta') -->
@endsection
